In [1]:
import numpy as np
current_state = np.random.get_state()

# produce some random numbers:
a = np.random.randn(3)
print(a)

# Now, restoring the RNG state and producing again 3 random numbers, you get the same result:

np.random.set_state(current_state)
b = np.random.randn(3)
print(b)
a == b

[ 1.04127023  0.10822797 -1.44079725]
[ 1.04127023  0.10822797 -1.44079725]


array([ True,  True,  True], dtype=bool)

In simulation, large amount of cheap (easily computed) random numbers are required. In general, consider how random numbers might be obtained:

1. Dice, coins, colored balls
2. Specially designed electronic equipment 
3. Algorithms.

In general we depend agresively of Algorithms. But Algorithms can't create a real random Number.
A good read can be this article about [a real case of random generated numbers](https://www.fastcodesign.com/90137157/the-hardest-working-office-design-in-america-encrypts-your-data-with-lava-lamps)


What are a few usages of random numbers?

* Simulation
* VideoGames
* Gambling
* Security (Encryption, 2-factor authentication, etc)
* Cryptography (Digital Signing, etc)


> **Definition 1 (Pseudorandom Numbers):** A sequence of pseudorandom numbers, Ui, is a deterministic sequence of numbers in (0, 1) having the same relevant statistical prop- erties as a sequence of truly random U(0, 1) numbers. 


A set of statistical tests are performed on the pseudorandom numbers generated from algorithms in order to indicate that their properties are not signicantly different from a true set of U(0, 1) random numbers.

The algorithms that produce pseudorandom numbers are called **random number generators**. 

**Definition 2:** 
An LCG defines a sequence of integers, $R_0,R_1, ...$ between 0 and m − 1 according to the following recursive relationship, where i = 0, 1, 2, ...:

\begin{equation*} R_{(i+1)} = (aR_i + c) \,mod \text{ m for i = 0,1,2,...} \end{equation*}  

where R0 is called the seed of the sequence, a is called the constant multiplier, c is called the increment, and m is called the modulus. $(m, a, c, R_0 )$  are integers with $ a > 0, c≥0,m>a,m>c,m>R_0$ ,and $ 0≤R_i ≤m−1$ .


To compute the corresponding pseudorandom uniform number, we use \begin{equation*} U_i = R_i/m\end{equation*}

## Exercise 1: 
Consider an LCG with parameters $(m = 8, a = 5, c = 1, R_0 = 5)$. Compute the first nine values for $R_i$ and $U_i$ from the defined sequence.


First of all, we need to remember what the modulus is:

\begin{align*}
z\,=\,y\,mod\,m
R_1 =(5R_0 +1)\,mod\,8 = 26\,mod\,8\,=\,2\,⇒\,U_1 \,= 0.25 \\
R_2 =(5R_1\, +1)\,mod\,8\,=\,11\,mod\,8\,=\,3\,⇒\,U_2 =\,0.375 \\ 
R_3 =(5R_2 +1)mod\,8=16\,mod\,8\,=\,0\,⇒\,U_3 =\,0.0 \\
R_4 =(5R_3 +1)mod\,8=1\,mod\,8=1⇒\,U_4 =\,0.125 \\
R_5 =6⇒U_5 =0.75 \\
R_6 =7⇒U_6 =0.875 \\ 
R_7 =4⇒U_7 =0.5 \\
R_8 =5⇒U_8 =0.625 \\
R_9 =2⇒U_9 =0.25
\end{align*}


A good way of expressing this in a software is the following


In [2]:
def linear_congruential_generator(modulus, constant_multiplier, constant, seed):
    _xn = seed

    while True:
        yield _xn
        _xn = (constant_multiplier * _xn + constant) % modulus
        
# create the first 12 elements

In [5]:
# Exercise 1 Proof
generator = linear_congruential_generator(8, 5, 1, 5)

for i in range(15):
    random_number = next(generator)
    print('R{} = {}, U{} = {}'.format(i, random_number, i, random_number/8.0))
        
    

R0 = 5, U0 = 0.625
R1 = 2, U1 = 0.25
R2 = 3, U2 = 0.375
R3 = 0, U3 = 0.0
R4 = 1, U4 = 0.125
R5 = 6, U5 = 0.75
R6 = 7, U6 = 0.875
R7 = 4, U7 = 0.5
R8 = 5, U8 = 0.625
R9 = 2, U9 = 0.25
R10 = 3, U10 = 0.375
R11 = 0, U11 = 0.0
R12 = 1, U12 = 0.125
R13 = 6, U13 = 0.75
R14 = 7, U14 = 0.875


**Theorem 1 (LCG Full Period Conditions):** An LCG has full period if and only if the following three conditions hold:
1. The only positive integer that (exactly) divides both $m$ and $c$ is $1$ (i.e., $c$ and $m$ have no common factors other than $1$).
2. If $q$ is a prime number that divides $m$ then $q$ should divide $(a−1)$ (i.e., $(a−1)$ is a multiple of every prime number that divides $m$).
3. If $4$ divides $m$, then $4$ should divide $(a−1)$ (i.e., $(a−1)$ is a multiple of $4$ if $m$ is a multiple of $4$).


**Exercise 2:** Let's Check if LCG reaches Full Period

Let's use Theorem 1 to proof this.

* **Condition 1:** $c$ and $m$ have no common factors other than $1$.
The factors of $m$ = $8$ are $(1, 2, 4, 8)$, since $c = 1$ (with factor 1) condition 1 is true.
* **Condition 2:** $(a − 1)$ is a multiple of every prime number that divides m. The  first few prime numbers are $(1, 2, 3, 5, 7)$. The prime numbers, $q$, that divide $m = 8$ are $(q = 1, 2)$. Since $a = 5$ and $(a − 1) = 4$, clearly $q = 1$ divides $4$ and $q = 2$ divides $4$. Thus, condition 2 is true.
* **Condition 3:** If $4$ divides $m$, then $4$ should divide $(a − 1)$.
Since $m = 8$, clearly $4$ divides $m$. Also, 4 divides $(a − 1) = 4$. Thus, condition 3 holds.

# Exercises

Analyze the following LCG: $X_i = (11X_i - _1 + 5)(mod (16)), X_0 = 1$ using Theorem 1.

(a) What is the maximum possible period length for this generator? Does this generator achieve the maximum possible period length? Justify your answer.

(b) Generate two pseudorandom uniform numbers for this generator.

In [7]:
# The only positive integer that (exactly) divides both  m  and  c,  is  1  (i.e., 
# cc  and  mm  have no common factors other than  11 ).
m = 16; m_factors = [1, 2, 4, 8, 16]
c = 5; c_factors = [1,5]
# If  q  is a prime number that divides  m  then  qq  should divide  (a−1) 
# (i.e.,  (a−1)(a−1)  is a multiple of every prime number that divides  mm ).
a = 11; b = a-1 # 10
# True
# If  4  divides  m , then  4  should divide  (a−1)  (i.e.,  (a−1)(a−1)  is a multiple of  44  if  mm  is a multiple of  44 ).
# False

# Exercise 1 Proof
generator = linear_congruential_generator(16, 11, 5, 1)

for i in range(16):
    random_number = next(generator)
    print('R{} = {}, U{} = {}'.format(i, random_number, i, random_number/8.0))

R0 = 1, U0 = 0.125
R1 = 0, U1 = 0.0
R2 = 5, U2 = 0.625
R3 = 12, U3 = 1.5
R4 = 9, U4 = 1.125
R5 = 8, U5 = 1.0
R6 = 13, U6 = 1.625
R7 = 4, U7 = 0.5
R8 = 1, U8 = 0.125
R9 = 0, U9 = 0.0
R10 = 5, U10 = 0.625
R11 = 12, U11 = 1.5
R12 = 9, U12 = 1.125
R13 = 8, U13 = 1.0
R14 = 13, U14 = 1.625
R15 = 4, U15 = 0.5


**Definition 3 (Random Number Stream):** The subsequence of random numbers generated from a given seed is called a random number stream.

## Other alternatives

With today’s modern computers, even $m$ is $2^{31} − 1 = 2, 147, 483, 647$ is not very big. For large simulations, you can easily run through all these random numbers.

Given current computing power, the previously discussed PMMLCGs are insuf cient since it is likely that all the 2 billion or so of the random numbers would be used in per- forming serious simulation studies. Thus, a new class of random number generators that have extremely long periods was developed. The random number generator described in L’Ecuyer et al. [2002] is one example of such a generator. It is based on the combina- tion of two multiple recursive generators resulting in a period of approximately $3.1 × 10^{57}$.

This is the same generator that is now used in many commercial simulation packages.



## References

[How Computers generate random numbers ](https://www.howtogeek.com/183051/htg-explains-how-computers-generate-random-numbers/)

\begin{align*}
R_{1, i} = (1, 403, 580R_{1, i-2} - 810,728 R_{1, i-3})[mod(2^{32} - 209)] \\ 
R_{2, i} = (527,612R_{2, i-1} - 1,370,589 R_{2, i-3})[mod(2^{32} - 22,853)] 
\end{align*}

\begin{align*}
Y_i = (R_{1,i} - R_{2,i})[mod(2^32 - 209)] \\
U_i = Y_1 /{ 2^32 - 209}
\end{align*}